# name: Reverse brute solver
# on:
#   push:
#     branches:
#       - 'main'
#   schedule:
#     - cron: '0 2 * * *'

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: âš™ï¸ Checkout repo
#         uses: actions/checkout@v2
#       - name: ğŸ  Setup Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.8
#       - name: ğŸ§° Install dependencies
#         run: |
#           pip3 install requests python-dotenv
#       - name: ğŸ‹ï¸â€â™‚ï¸ Execute reverse brute python script
#         run: |
#           python3 reverse_brute.py
